"""fee rules

Revision ID: 06f477e6de04
Revises: 77389eb1f1f3
Create Date: 2026-07-09 15:32:01.205980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f477e6de04'
down_revision: Union[str, None] = '77389eb1f1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_rules',
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=True),
    sa.Column('kyc_level', sa.Integer(), nullable=True),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_rules_fee_type'), 'fee_rules', ['fee_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fee_rules_fee_type'), table_name='fee_rules')
    op.drop_table('fee_rules')
    # ### end Alembic commands ###
