"""fx rates and card payments

Revision ID: 348b00047977
Revises: d33011be19a1
Create Date: 2026-07-07 03:53:30.729451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348b00047977'
down_revision: Union[str, None] = 'd33011be19a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_base_currency'), 'fx_rates', ['base_currency'], unique=False)
    op.create_index(op.f('ix_fx_rates_quote_currency'), 'fx_rates', ['quote_currency'], unique=False)
    op.create_table('card_transactions',
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('merchant_name', sa.String(length=150), nullable=False),
    sa.Column('merchant_country', sa.String(length=2), nullable=True),
    sa.Column('merchant_currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('local_currency', sa.String(length=3), nullable=False),
    sa.Column('local_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fees_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_debited', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decline_reason', sa.String(length=50), nullable=True),
    sa.Column('provider_reference', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_reference')
    )
    op.create_index(op.f('ix_card_transactions_card_id'), 'card_transactions', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_transactions_card_id'), table_name='card_transactions')
    op.drop_table('card_transactions')
    op.drop_index(op.f('ix_fx_rates_quote_currency'), table_name='fx_rates')
    op.drop_index(op.f('ix_fx_rates_base_currency'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
