"""compliance alerts

Revision ID: 37a6f235353c
Revises: 9d398e0208d3
Create Date: 2026-07-09 15:47:08.847807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37a6f235353c'
down_revision: Union[str, None] = '9d398e0208d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_alerts_alert_type'), 'compliance_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_status'), 'compliance_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_alerts_user_id'), 'compliance_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_alerts_user_id'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_status'), table_name='compliance_alerts')
    op.drop_index(op.f('ix_compliance_alerts_alert_type'), table_name='compliance_alerts')
    op.drop_table('compliance_alerts')
    # ### end Alembic commands ###
