"""limit rules

Revision ID: 3e6ee9b95773
Revises: e002b32054e3
Create Date: 2026-07-09 15:18:51.830073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6ee9b95773'
down_revision: Union[str, None] = 'e002b32054e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limit_rules',
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('kyc_level', sa.Integer(), nullable=True),
    sa.Column('limit_type', sa.String(length=40), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limit_rules_limit_type'), 'limit_rules', ['limit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_limit_rules_limit_type'), table_name='limit_rules')
    op.drop_table('limit_rules')
    # ### end Alembic commands ###
